### ISSUE TITLE
能否支持一下非微职位视频

### ISSUE THREAD

**Issue by ghost** [abusizhishen/51cto-video-download#1]
如题，目前买的不是微职位的课程，在网页看断断续续老卡，所以想下载下来看，不知您是否有时间帮忙支持一下。这里的课程https://edu.51cto.com/courselist/index.html

**Comment by abusizhishen** [comment]
> 如题，目前买的不是微职位的课程，在网页看断断续续老卡，所以想下载下来看，不知您是否有时间帮忙支持一下。这里的课程https://edu.51cto.com/courselist/index.html

目前下载已不是问题，但是视频被加密，无法观看，我正在寻求解决方法。

**Comment by u-raison** [comment]
@abusizhishen    我测试了一下，没问题啊。你代码写的很好就是几个bug

1、windows校验特殊字符不不够多，比如 有的课程有 冒号
2、几个函数直接breack，可以continue，因为部分课程的某节lesson并不是视频，可能是课后习题，所以无法get m3u8和download m3u8
3、获取已购买课程的api接口弄错了，是ajax-get-order-list，你那个接口会导致漏了一些教程。

**Comment by u-raison** [comment]
不好意思 ，看错仓库了，我是说这个仓库：https://github.com/qiaoxingxing/51cto-video-download

**Comment by abusizhishen** [comment]
> 如题，目前买的不是微职位的课程，在网页看断断续续老卡，所以想下载下来看，不知您是否有时间帮忙支持一下。这里的课程https://edu.51cto.com/courselist/index.html

已支持，并且下载后可直接观看
